### ISSUE TITLE
cargo-quickinstall --uninstall packagename

### ISSUE THREAD

**Issue by alsuren** [cargo-bins/cargo-quickinstall#71]
* re-fetch the binary package
* run it through tar to list the contents
* delete each file in the tar archive from bin/.

**Comment by Milo123459** [comment]
hey - was wondering if there are any updates on this. are there any hacky workarounds that would mean you could use regular `cargo uninstall`?

**Comment by NobodyXu** [comment]
> are there any hacky workarounds that would mean you could use regular `cargo uninstall`?

That's an interesting suggestion, I didn't know `cargo-uninstall` exists.

It turns out that it works with `cargo-binstall` as expected since it updates `.cargo/.crates.toml`, though there's still some bug on cargo-binstall.

`cargo-binstall` can install pre-built binaries from quickinstall, so you can give it a shot.

For `cargo-quickinstall` to support this, it can use binstalk-manifest to update `.cargo/.crates.toml` and then it will work as intended.

**Comment by alsuren** [comment]
I think the eventual solution for this might be "bootstrap by installing cargo-binstall from binaries and then turn cargo-quickinstall into a thin shim around cargo-binstall, because it does a better job at updating metadata etc"

It may also be possible to port across their code for doing this, but it feels like it would add complexity that would make our compile times longer.

**Comment by Milo123459** [comment]
i think we can just manually update .cargo/.crates.toml - this would be extremely useful.

**Comment by NobodyXu** [comment]
> i think we can just manually update .cargo/.crates.toml - this would be extremely useful.

It can done using binstalk-manifest, a MIT library for this.

**Comment by Milo123459** [comment]
this increases the compile time on this crate by a lot due to it having a lot of dependencies. i reckon manually doing it would also work, but im not sure

**Comment by NobodyXu** [comment]
> this increases the compile time on this crate by a lot due to it having a lot of dependencies. i reckon manually doing it would also work, but im not sure

While it does contain some extra dependencies that can be removed if you develop an in-house solution, I don't think it's worth the effort.

Its dependencies are already quite minimal and with caching, the added compilation time should be minimal compared to in-house one because the crates that really takes a long time to compile are the ones that have to be used:
 - `toml`/`toml_edit` (`toml` in the future might just be a wrapper of `toml_edit` after compile-time and runtime performance of it improves)
 - `serde_json`
 - `url`
 - `thiserror`
 - `semver`
 - `serde`

Something like `miette` is a bit unnecessary, takes some time to compile and perhaps we can add a feature flag for that, but that is about it.

`toml_edit` is the one taking the longest in the release build on my M1, `url` brings a lot of dependencies, `serde`/`thiserror` brings in `serde_derive` and `semver` contains quite some code.

**Comment by NobodyXu** [comment]
> I think the eventual solution for this might be "bootstrap by installing cargo-binstall from binaries and then turn cargo-quickinstall into a thin shim around cargo-binstall, because it does a better job at updating metadata etc"

In that case, a shell script might be enough, though I'm not 100% sure since the arg parsing might still worth the time writing proper Rust code.

**Comment by alsuren** [comment]
The cargo-quickinstall client is basically a glorified shell script that calls out to curl and tar. I like it that way. Once `-Z sparse_registry` becomes stable, you will be able to reliably install cargo-quickinstall from source in ~5 seconds, and that is quite valuable for the CI usecase.

It would be good to have a default mode that uses binstall, and a fallback mode (used for bootstrapping binstall and maybe also if the `CI` environment variable is set) that just uses curl and tar as we currently do (and leaves cargo's metadata alone as it currently does, because it doesn't matter in ci). Maybe we print a warning about it and have a way to force using binstall even in CI?

This would allow us to close a handful of bugs in the client while keeping out build times low, and would let us focus on the repository side of the project.

**Comment by NobodyXu** [comment]
> used for bootstrapping binstall and maybe also if the CI environment variable is set

I think cargo-binstall is ready to use in CI.
In fact, it probably supports more crates than quick-install alone, since it can download binaries provided by the maintainer.

**Comment by Milo123459** [comment]
Hmm. I still think manually editing it should be fine? The file in question is just a toml file containing the names of crates>

**Comment by NobodyXu** [comment]
> Hmm. I still think manually editing it should be fine? The file in question is just a toml file containing the names of crates.

You can certainly do that, but then you have to write the code yourself.

The `.crates.toml` is quite strange actually, the keys contains the crate name, version, source while the value being the binaries installed.

When updating it, you must first remove all keys that contain the crate name.

**Comment by Milo123459** [comment]
Oh lord, that's gonna suck. Maybe I can reverse-engineer some of the stuff from the binstall crate?

**Comment by NobodyXu** [comment]
> Oh lord, that's gonna suck. Maybe I can reverse-engineer some of the stuff from the binstall crate?

You can just copy from binstalk-manifest if you want, it's using MIT license.

**Comment by NobodyXu** [comment]
> It would be good to have a default mode that uses binstall, and a fallback mode (used for bootstrapping binstall and maybe also if the CI environment variable is set) that just uses curl and tar as we currently do (and leaves cargo's metadata alone as it currently does, because it doesn't matter in ci). Maybe we print a warning about it and have a way to force using binstall even in CI?

I would open a PR later for this to use binstall unless it's forced not to when I am free.
